#!/usr/bin/env python

# Documentation of 'plotfile' see -
# http://matplotlib.org/api/pyplot_api.html#module-matplotlib.pyplot

# This script is used to plot the data generated by - 'test_airsea'

from pylab import plotfile, show, gca, savefig

fname="kondo.cd"
plotfile(fname, (0,1,2,3), delimiter=' ',subplots=False, newfig=False)
savefig('kondo.png')
show()

fname="kara2000.cd"
plotfile(fname, (0,1,2,3), delimiter=' ',subplots=False, newfig=True)
savefig('kara2000.png')
show()

fname="kara2005.cd"
plotfile(fname, (0,1,2,3), delimiter=' ',subplots=False, newfig=False)
savefig('kara2005.png')
show()
